process.env.NODE_ENV='test';
jest.mock('../config/prisma',()=>({support_tickets:{findMany:jest.fn(),findFirst:jest.fn(),create:jest.fn(),update:jest.fn()},studios:{findMany:jest.fn(),findUnique:jest.fn()},assets:{count:jest.fn()},albums:{findFirst:jest.fn()},customers:{findFirst:jest.fn()},$transaction:jest.fn()}));
jest.mock('../config/rabbitmq',()=>({publishToQueue:jest.fn()}));
const prisma=require('../config/prisma');const support=require('../controllers/supportController');const folders=require('../controllers/folderController');
function response(){return {status:jest.fn().mockReturnThis(),json:jest.fn()};}
beforeEach(()=>jest.clearAllMocks());
test('studio ticket list is tenant scoped',async()=>{prisma.support_tickets.findMany.mockResolvedValue([]);prisma.studios.findMany.mockResolvedValue([]);await support.list({studioId:'studio-a'},response(),jest.fn());expect(prisma.support_tickets.findMany.mock.calls[0][0].where).toEqual({studio_id:'studio-a'});});
test('ticket creation ignores client supplied foreign studio context',async()=>{prisma.studios.findUnique.mockResolvedValue({id:'studio-a'});prisma.support_tickets.create.mockResolvedValue({id:'ticket'});const res=response();await support.create({studioId:'studio-a',user:{id:'user-a'},body:{studio_id:'studio-b',subject:'Upload fails',description:'Permission denied',category:'upload',priority:'high'}},res,jest.fn());expect(prisma.support_tickets.create.mock.calls[0][0].data).toMatchObject({studio_id:'studio-a',created_by:'user-a',subject:'Upload fails'});expect(res.status).toHaveBeenCalledWith(201);});
test('invalid ticket priority is rejected before writes',async()=>{const res=response();await support.create({studioId:'studio-a',user:{id:'u'},body:{subject:'Issue',description:'Details',priority:'unlimited'}},res,jest.fn());expect(res.status).toHaveBeenCalledWith(400);expect(prisma.support_tickets.create).not.toHaveBeenCalled();});
test('ticket updates cannot modify a different studio',async()=>{prisma.support_tickets.findFirst.mockResolvedValue(null);const res=response();await support.update({studioId:'a',params:{id:'foreign'},body:{status:'resolved'}},res,jest.fn());expect(res.status).toHaveBeenCalledWith(404);expect(prisma.support_tickets.update).not.toHaveBeenCalled();});
test('batch assignment rejects foreign assets before album creation',async()=>{prisma.assets.count.mockResolvedValue(0);const res=response();await folders.batchAssignAssets({studioId:'a',body:{asset_ids:['foreign'],new_album_title:'Shoot'}},res,jest.fn());expect(res.status).toHaveBeenCalledWith(400);expect(prisma.$transaction).not.toHaveBeenCalled();});
