import React,{useEffect,useState} from 'react';
import api from '../../api/client';
import {useAuthStore} from '../../stores/authStore';
import {Modal} from '../../components/ui/modal';
import {Button} from '../../components/ui/button';
import {toast} from '../../components/ui/toast';
const statuses=['open','in_progress','waiting','resolved','closed'];
const blank={studio_id:'',subject:'',description:'',category:'general',priority:'normal'};
export function SupportTicketsPage({studio=false}) {
 const [tickets,setTickets]=useState([]),[studios,setStudios]=useState([]),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[active,setActive]=useState(null),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const studioId=useAuthStore(s=>s.currentStudio?.id);
 const base=studio?'/studio':'/admin';
 async function load(){try{setLoading(true);setError('');const {data}=await api.get(base+'/support-tickets');setTickets(data);if(!studio){const r=await api.get('/admin/studios');setStudios(r.data);}}catch(e){setError(e.response?.data?.error||'Could not load tickets');}finally{setLoading(false);}}
 useEffect(()=>{load();},[base,studioId]);
 async function save(e){e.preventDefault();try{setBusy(true);if(active)await api.patch(base+'/support-tickets/'+active.id,{status:active.status,priority:active.priority,resolution:active.resolution||''});else await api.post(base+'/support-tickets',form);setOpen(false);toast.success(active?'Ticket updated':'Ticket created');await load();}catch(e){toast.error(e.response?.data?.error||'Could not save ticket');}finally{setBusy(false);}}
 const filtered=tickets.filter(t=>(status==='all'||t.status===status)&&`${t.subject} ${t.description} ${t.studio?.name} ${t.id}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="page-enter space-y-6"><div className="page-heading"><div><p className="eyebrow">STUDIO SUPPORT</p><h1>Support tickets</h1><p className="page-description">Track issues, priorities, progress and resolutions in one place.</p></div><Button onClick={()=>{setActive(null);setForm({...blank,studio_id:studios[0]?.id||''});setOpen(true);}}>New ticket</Button></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-4">{['open','in_progress','waiting','resolved'].map(s=><button key={s} className="panel p-5 text-left" onClick={()=>setStatus(s)}><span className="text-sm text-muted capitalize">{s.replace('_',' ')}</span><strong className="block text-3xl mt-2">{tickets.filter(t=>t.status===s).length}</strong></button>)}</div>
 <div className="media-toolbar"><input className="search-input" aria-label="Search tickets" placeholder="Search issue, studio or ticket ID…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Ticket status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><Button variant="outline" onClick={load}>Refresh</Button></div>
 {error&&<p role="alert" className="form-error">{error}</p>}{loading?<p role="status">Loading tickets…</p>:<div className="space-y-3">{filtered.map(t=><button key={t.id} className="panel p-5 w-full text-left flex flex-wrap justify-between gap-4" onClick={()=>{setActive(t);setOpen(true);}}><div><p className="text-xs text-muted">#{t.id.slice(0,8)} · {t.studio?.name} · {t.category}</p><h2 className="font-semibold text-lg my-1">{t.subject}</h2><p className="text-sm text-muted line-clamp-2">{t.description}</p></div><div className="text-sm"><p className="capitalize">{t.status.replace('_',' ')}</p><p className={t.priority==='urgent'?'text-red-500':'text-muted'}>{t.priority} priority</p></div></button>)}{!filtered.length&&<p className="panel p-10 text-center text-muted">No matching tickets.</p>}</div>}
 <Modal open={open} onOpenChange={setOpen} title={active?'Ticket #'+active.id.slice(0,8):'New support ticket'} description="Describe the issue and track its resolution."><form className="form-stack" onSubmit={save}>{active?<><h3 className="font-semibold">{active.subject}</h3><p className="whitespace-pre-wrap text-sm">{active.description}</p><label>Status<select value={active.status} onChange={e=>setActive({...active,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Priority<select value={active.priority} onChange={e=>setActive({...active,priority:e.target.value})}>{['low','normal','high','urgent'].map(s=><option key={s}>{s}</option>)}</select></label><label>Resolution / progress notes<textarea rows={5} maxLength={10000} value={active.resolution||''} onChange={e=>setActive({...active,resolution:e.target.value})}/></label></>:<>{!studio&&<label>Studio<select required value={form.studio_id} onChange={e=>setForm({...form,studio_id:e.target.value})}><option value="">Choose studio</option>{studios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>Subject<input required maxLength={200} value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><div className="form-grid"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['general','camera','upload','gallery','account','billing','bug'].map(s=><option key={s}>{s}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['low','normal','high','urgent'].map(s=><option key={s}>{s}</option>)}</select></label></div><label>Issue description<textarea required rows={5} maxLength={10000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></>}<div className="modal-actions"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy} type="submit">{busy?'Saving…':'Save ticket'}</Button></div></form></Modal></div>;
}
