const router = require('express').Router();
const controller = require('../controllers/customerController');
const { authenticate } = require('../middlewares/auth');
const { privateLiveStream } = require('../services/mediaAccess');
router.use(authenticate);
router.get('/assets/:id/view', controller.serveCustomerAsset);
router.get('/albums/live-stream', privateLiveStream);
router.get('/albums', controller.getMyGalleries);
router.get('/albums/:id', controller.getAlbumById);
module.exports = router;
